config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :accounts, only: [:new, :create, :show]
  get "/about", to: "about#index", as: :about

  namespace :admin do
    resources :contents
  end

  root to: "home#index", as: :home
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
  end

  def create
    @account = Account.create(account_params)
    redirect_to account_path @account
  end

  def show
    @account = Account.find(params[:id])
  end

  private

  def account_params
    params.require(:account).permit!
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
  before_action :check_admin!

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.create(content_params)
    redirect_to admin_contents_path
  end

  def update
    @content = Content.find(params[:id])
    @content.update(content_params)
    redirect_to admin_contents_path
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
  end

  private

  def content_params
    params.require(:content).permit!
  end

  def check_admin!
    redirect_to home_path unless admin_signed_in?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.haml
North Park Fincanl Planning is all about planning your financials!

app/views/accounts/_form.html.haml
.accounts.submitable
  = semantic_form_for @account do |f|
    = f.input :full_name, label: "Full Name"
    = f.input :email
    = f.button class: "submit" do
      %span
        Get Started

app/views/accounts/new.html.haml
%h1
  Sign Up
= render "form"

app/views/accounts/show.html.haml
= @account.full_name
= @account.email

app/views/admin/contents/_form.html.haml
.submitable
  = semantic_form_for [:admin, @content] do |f|
    = f.input :name
    = f.input :body
    = f.button class: "submit" do
      %span
        done

app/views/admin/contents/edit.html.haml
%h1
  = "Editing '#{@content.name}'"
= render "form"

app/views/admin/contents/index.html.haml
.contents
  %h1
    Manage Your Content
  - if @contents.empty?
    %h2
      There is no content yet
    .submitable
      = button_to new_admin_content_path, class: "submit", method: :get do
        %span
          create new content
  - else
    %table.table
      %thead
        %tr
          %th Name
          %th Location
          %th Author
          %th Action
      %tbody
        - @contents.each do |content|
          %tr
            %td= content.name
            %td Blah
            %td Blah
            %td= link_to "Edit", edit_admin_content_path(content)

app/views/admin/contents/new.html.haml
%h1
  Create a new piece of content
= render "form"

app/views/admin/contents/show.html.haml
= @content.name
= @content.body

app/views/home/index.html.haml
.home-hero.content-centered
  .text
    .logo
    .h1.title
      North Park
    .h3.subtitle
      Financial Planning

app/views/layouts/_top_nav.html.haml
.top-nav
  %ul
    %li.logo
    %li
      = link_to "home", home_path
    %li
      = link_to "get started", new_account_path
    %li
      = link_to "learn more about us", about_path
    %li
      = link_to "pricing", "#"
    %li
      = link_to "contact", "#"
    - if admin_signed_in?
      %li.admin
        = link_to "manage content", admin_contents_path
      %li.admin
        = link_to "sign out", destroy_admin_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title North Park Financial Planning
    = csrf_meta_tags
    = favicon_link_tag asset_path("logo_ico.png"), rel: "icon", type:  "image/png"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/top_nav"
    .main-content
      = yield